package com.aliernfrog.lactool.util

import com.aliernfrog.lactool.R
import io.github.aliernfrog.shared.util.SharedString

val sharedString = SharedString(
    appName = R.string.app_name,
    actionBack = R.string.action_back,
    actionCancel = R.string.action_cancel,
    actionClose = R.string.action_close,
    actionDelete = R.string.action_delete,
    actionDismiss = R.string.action_dismiss,
    actionOK = R.string.action_ok,
    actionOpenInBrowser = R.string.action_openInBrowser,
    actionExpand = R.string.action_expand,
    actionCollapse = R.string.action_collapse,
    infoDeleteQuestion = R.string.info_deleteQuestion,
    infoPleaseWait = R.string.info_pleaseWait,
    warning = R.string.warning,
    warningError = R.string.warning_error,
    warningErrorTapToReport = R.string.warning_error_tapToReport,

    mediaOverlayGuide = R.string.mediaOverlay_guide,
    mediaOverlayGuideToggleOverlay = R.string.mediaOverlay_guide_toggleOverlay,
    mediaOverlayGuideToggleZoom = R.string.mediaOverlay_guide_toggleZoom,
    mediaOverlayGuideZoom = R.string.mediaOverlay_guide_zoom,

    settings = R.string.settings,
    settingsAbout = R.string.settings_about,
    settingsAboutDescription = R.string.settings_about_description,
    settingsAboutUpdates = R.string.settings_about_updates,
    settingsAboutUpdatesAutoCheckUpdates = R.string.settings_about_updates_autoCheckUpdates,
    settingsAboutUpdatesAutoCheckUpdatesDescription = R.string.settings_about_updates_autoCheckUpdates_description,
    settingsAboutIssues = R.string.settings_about_issues,
    settingsAboutIssuesTitle = R.string.settings_about_issues_title,
    settingsAboutIssuesDescription = R.string.settings_about_issues_description,
    settingsAboutIssuesCopyDebugInfo = R.string.settings_about_issues_copyDebugInfo,
    settingsAboutIssuesCopyDebugInfoDescription = R.string.settings_about_issues_copyDebugInfo_description,
    settingsAboutIssuesCopyDebugInfoClipLabel = R.string.settings_about_issues_copyDebugInfo_clipLabel,
    settingsAboutIssuesCopyDebugInfoCopied = R.string.settings_about_issues_copyDebugInfo_copied,
    settingsAboutCredits = R.string.settings_about_credits,
    settingsAboutLibs = R.string.settings_about_libs,
    settingsAboutLibsDescription = R.string.settings_about_libs_description,
    settingsAboutLibsLicense = R.string.settings_about_libs_license,
    settingsAboutLibsWebsite = R.string.settings_about_libs_website,
    settingsAboutLibsOrganization = R.string.settings_about_libs_organization,
    settingsAboutChangelog = R.string.settings_about_changelog,
    settingsAboutUpdate = R.string.settings_about_update,
    settingsAppearance = R.string.settings_appearance,
    settingsAppearanceDescription = R.string.settings_appearance_description,
    settingsAppearanceTheme = R.string.settings_appearance_theme,
    settingsAppearanceThemeSystem = R.string.settings_appearance_theme_system,
    settingsAppearanceThemeLight = R.string.settings_appearance_theme_light,
    settingsAppearanceThemeDark = R.string.settings_appearance_theme_dark,
    settingsAppearanceColors = R.string.settings_appearance_colors,
    settingsAppearanceColorsMaterialYou = R.string.settings_appearance_materialYou,
    settingsAppearanceColorsMaterialYouDescription = R.string.settings_appearance_materialYou_description,
    settingsAppearanceColorsMaterialYouUnavailable = R.string.settings_appearance_materialYou_unavailable,
    settingsAppearanceColorsPitchBlack = R.string.settings_appearance_pitchBlack,
    settingsAppearanceColorsPitchBlackDescription = R.string.settings_appearance_pitchBlack_description,
    settingsExperimental = R.string.settings_experimental,
    settingsExperimentalDescription = R.string.settings_experimental_description,
    settingsUpdateNotificationUpdateAvailable = R.string.settings_updateNotification_updateAvailable,
    settingsUpdateNotificationDescription = R.string.settings_updateNotification_description,

    updates = R.string.updates,
    updatesChangelog = R.string.updates_changelog,
    updatesIncompatible = R.string.updates_incompatible,
    updatesNoChangelog = R.string.updates_noChangelog,
    updatesCheckUpdates = R.string.updates_checkUpdates,
    updatesCurrentVersion = R.string.updates_currentVersion,
    updatesPrerelease = R.string.updates_prerelease,
    updatesUpdate = R.string.updates_update,
    updatesUpdateAvailable = R.string.updates_updateAvailable,

    crashHandlerTitle = R.string.crashHandler_title,
    crashHandlerDescription = R.string.crashHandler_description,
    crashHandlerStackTrace = R.string.crashHandler_stackTrace,
    crashHandlerReport = R.string.crashHandler_report,
    crashHandlerSendReport = R.string.crashHandler_sendReport,
    crashHandlerSendReportSent = R.string.crashHandler_sendReport_sent,
    crashHandlerRestartApp = R.string.crashHandler_restartApp,
    crashHandlerSupport = R.string.crashHandler_support,
    crashHandlerSupportDescription = R.string.crashHandler_support_description,
    crashHandlerSupportGuide = R.string.crashHandler_support_guide,
    crashHandlerSupportCopyDetails = R.string.crashHandler_support_copyDetails
)