name: Build commit

on:
  push:
    branches-ignore:
      - 'legacy'
      - 'v**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: ./app/build/outputs/apk/release/
          signingKey: ${{ secrets.KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename signed APK
        run: mv ${{steps.sign_apk.outputs.signedFile}} lactool.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lactool
          path: lactool.apk