name: Crowdin sync

on:
  workflow_dispatch:
  
  push:
    branches: [ "dev" ]
  
  schedule:
    - cron: "0 17 * * 5"

jobs:
  sync-crowdin:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Crowdin sync
        uses: crowdin/github-action@v2.0.0
        with:
          create_pull_request: true
          pull_request_title: "feat(l10n): update translations"
          pull_request_base_branch_name: "dev"
          crowdin_branch_name: "dev"
          localization_branch_name: "l10n"
          commit_message: "feat(l10n): update translations"
          upload_sources: true
          upload_translations: true
          download_translations: true
          skip_untranslated_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
