name: Release in Artifacts (Old codebase)

on:
  push:
    branches: ["old-codebase"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gradle build
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./app/build/outputs/apk/release/
          signingKeyBase64: ${{ secrets.OLD_KEYSTORE_BASE64 }}
          alias: ${{ secrets.OLD_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.OLD_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.OLD_KEY_PASSWORD }}

      - name: Rename signed APK
        run: mv ${{steps.sign_apk.outputs.signedReleaseFile}} lactool.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lactool
          path: lactool.apk