name: Release alpha

on:
  push:
    tags:
      - "v**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Build with Gradle
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/key.jks
          ./gradlew packageReleaseUniversalApk -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/key.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename signed APK
        run: mv app/build/outputs/apk_from_bundle/release/app-release-universal.apk lactool.apk

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          excludeTypes: build,chore,ci,docs,other,style
      
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          prerelease: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          artifacts: "lactool.apk"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lactool
          path: lactool.apk
      
      - name: Check if workflow supplied
        id: check-workflow
        run: |
          if [ "$SECRET" == "" ]; then
            echo "present=NO" >> $GITHUB_OUTPUT
          else
            echo "present=YES" >> $GITHUB_OUTPUT
          fi
        env:
          SECRET: ${{ secrets.VERSION_DATA_WORKFLOW }}

      - name: Trigger workflow
        if: steps.check-workflow.outputs.present == 'YES'
        uses: fjogeleit/http-request-action@v1.15.2
        with:
          url: ${{ secrets.VERSION_DATA_WORKFLOW }}
          method: "POST"
          customHeaders: '{ "Accept":"application/vnd.github+json", "Authorization":"Bearer ${{ secrets.VERSION_DATA_TOKEN }}" }'
          data: '{ "ref":"main" }'